"""empty message

Revision ID: 2860992403d8
Revises: 
Create Date: 2023-10-30 09:42:07.443103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2860992403d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('apellido', sa.String(length=60), nullable=False),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('departamento',
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('cant_empleados', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_departamento')
    )
    op.create_table('empleado',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('apellido', sa.String(length=60), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('puesto', sa.String(length=60), nullable=True),
    sa.Column('sueldo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_empleado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleado')
    op.drop_table('departamento')
    op.drop_table('cliente')
    # ### end Alembic commands ###
