"""empty message

Revision ID: d2fcc50ce075
Revises: 2860992403d8
Create Date: 2023-10-31 09:47:09.612282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2fcc50ce075'
down_revision = '2860992403d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.drop_column('fecha_nacimiento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.DATE(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
