# Generated by Django 4.2.6 on 2023-10-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('ID_Alumno', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Edad', models.IntegerField()),
                ('Grado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('ID_Asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maestros',
            fields=[
                ('ID_Maestro', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Materia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('ID_Evento', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Fecha', models.DateField()),
                ('Responsable_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.maestros')),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('ID_Clase', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Horario', models.CharField(max_length=255)),
                ('Asignatura_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.asignaturas')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('ID_Calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('Calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Alumno_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.alumnos')),
                ('Asignatura_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.asignaturas')),
            ],
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='Maestro_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.maestros'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='Maestro_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.maestros'),
        ),
    ]
