"""empty message

Revision ID: 45b0c70b2e0d
Revises: 88d9ed4334f5
Create Date: 2023-12-04 20:57:26.049283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b0c70b2e0d'
down_revision = '88d9ed4334f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encargado', sa.String(length=250)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('encargado')

    # ### end Alembic commands ###
