"""empty message

Revision ID: 6b69f208518f
Revises: 
Create Date: 2023-11-06 10:18:37.220804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b69f208518f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventario',
    sa.Column('id_inv', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('precio_compra', sa.Float(), nullable=True),
    sa.Column('fecha_reab', sa.String(length=20), nullable=True),
    sa.Column('niv_min', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_inv')
    )
    op.create_table('producto',
    sa.Column('id_prod', sa.Integer(), nullable=False),
    sa.Column('nombre_pr', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_prod')
    )
    op.create_table('proveedor',
    sa.Column('id_prov', sa.Integer(), nullable=False),
    sa.Column('nombre_pv', sa.String(length=250), nullable=True),
    sa.Column('telefono_pv', sa.String(length=20), nullable=True),
    sa.Column('direccion_pv', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id_prov')
    )
    op.create_table('sucursal',
    sa.Column('id_suc', sa.Integer(), nullable=False),
    sa.Column('nombre_s', sa.String(length=250), nullable=True),
    sa.Column('direccion_s', sa.String(length=250), nullable=True),
    sa.Column('telefono_s', sa.String(length=20), nullable=True),
    sa.Column('horario', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_suc')
    )
    op.create_table('venta',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.String(length=20), nullable=True),
    sa.Column('cant_prod', sa.Integer(), nullable=True),
    sa.Column('total_venta', sa.Float(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_venta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta')
    op.drop_table('sucursal')
    op.drop_table('proveedor')
    op.drop_table('producto')
    op.drop_table('inventario')
    # ### end Alembic commands ###
